root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked

rules:
  '@typescript-eslint/unified-signatures': off

reportUnusedDisableDirectives: true
