name: npm-script-runner

on:
  workflow_call:
    inputs:
      npm-script:
        type: string
        required: true

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run ${{ inputs.npm-script }}
